### ISSUE TITLE
Take a look at Segno?

### ISSUE THREAD

**Issue by heuer** [shpaker/makeqr#5]
Hi Aleksandr,

Maybe you want to take a look at [Segno](https://github.com/heuer/segno) since
it could reduce your code and dependencies a lot.

It supports WIFI codes and PNG / SVG serialization.

```python

>>> form segno import helpers
>>> qr = helpers.make_wifi(ssid='My network', password='secret', security='WPA')
>>> qr.save('wifi_code.png')
>>> qr.save('wifi_code.svg')
```

For more information see <https://segno.readthedocs.io/en/stable/special-qrcode-factories.html#special-qr-code-factory-functions>

Best regards,
Lars

**Comment by shpaker** [comment]
Hi. Looks cool. But my script is too simple for something other than qrcode package.
